<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KhachHangSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $khachHangs = [
            [
                'ten_khach_hang' => 'Nguyễn Văn A',
                'so_dien_thoai' => '0911111111',
                'email' => 'nguyenvana@example.com',
                'dia_chi' => '12 Trần Hưng Đạo, Hoàn Kiếm, Hà Nội',
                'cong_no' => 0,
                'phi_chu' => null,
                'diem_tich_luy' => 150,
                'tong_chi_tieu' => 1500000,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(60),
                'updated_at' => $now->copy()->subDays(60),
            ],
            [
                'ten_khach_hang' => 'Trần Thị B',
                'so_dien_thoai' => '0922222222',
                'email' => 'tranthib@example.com',
                'dia_chi' => '45 Lê Lợi, Quận 1, TP.HCM',
                'cong_no' => 0,
                'phi_chu' => null,
                'diem_tich_luy' => 80,
                'tong_chi_tieu' => 800000,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(55),
                'updated_at' => $now->copy()->subDays(55),
            ],
            [
                'ten_khach_hang' => 'Lê Văn C',
                'so_dien_thoai' => '0933333333',
                'email' => null,
                'dia_chi' => '78 Bạch Đằng, Hải Châu, Đà Nẵng',
                'cong_no' => 500000,
                'phi_chu' => 'Nợ tiền hàng tháng trước',
                'diem_tich_luy' => 20,
                'tong_chi_tieu' => 200000,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(50),
                'updated_at' => $now->copy()->subDays(50),
            ],
            [
                'ten_khach_hang' => 'Phạm Thị D',
                'so_dien_thoai' => '0944444444',
                'email' => 'phamthid@example.com',
                'dia_chi' => '23 Nguyễn Văn Cừ, Long Biên, Hà Nội',
                'cong_no' => 0,
                'phi_chu' => null,
                'diem_tich_luy' => 200,
                'tong_chi_tieu' => 2000000,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(45),
                'updated_at' => $now->copy()->subDays(45),
            ],
            [
                'ten_khach_hang' => 'Hoàng Văn E',
                'so_dien_thoai' => '0955555555',
                'email' => 'hoangvane@example.com',
                'dia_chi' => '67 Phan Đình Phùng, Ba Đình, Hà Nội',
                'cong_no' => 0,
                'phi_chu' => null,
                'diem_tich_luy' => 50,
                'tong_chi_tieu' => 500000,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(40),
                'updated_at' => $now->copy()->subDays(40),
            ],
            [
                'ten_khach_hang' => 'Vũ Thị F',
                'so_dien_thoai' => '0966666666',
                'email' => 'vuthif@example.com',
                'dia_chi' => '101 Hai Bà Trưng, Quận 3, TP.HCM',
                'cong_no' => 0,
                'phi_chu' => null,
                'diem_tich_luy' => 320,
                'tong_chi_tieu' => 3200000,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(35),
                'updated_at' => $now->copy()->subDays(35),
            ],
            [
                'ten_khach_hang' => 'Đặng Văn G',
                'so_dien_thoai' => '0977777777',
                'email' => 'dangvang@example.com',
                'dia_chi' => '34 Lý Thường Kiệt, Hoàn Kiếm, Hà Nội',
                'cong_no' => 0,
                'phi_chu' => 'Khách VIP - ưu đãi 5%',
                'diem_tich_luy' => 580,
                'tong_chi_tieu' => 5800000,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(30),
                'updated_at' => $now->copy()->subDays(30),
            ],
            [
                'ten_khach_hang' => 'Bùi Thị H',
                'so_dien_thoai' => '0988888888',
                'email' => 'buithih@example.com',
                'dia_chi' => '89 Nguyễn Huệ, Quận 1, TP.HCM',
                'cong_no' => 0,
                'phi_chu' => null,
                'diem_tich_luy' => 90,
                'tong_chi_tieu' => 900000,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(28),
                'updated_at' => $now->copy()->subDays(28),
            ],
            [
                'ten_khach_hang' => 'Đỗ Văn I',
                'so_dien_thoai' => '0999999999',
                'email' => 'dovani@example.com',
                'dia_chi' => '56 Cầu Giấy, Hà Nội',
                'cong_no' => 0,
                'phi_chu' => null,
                'diem_tich_luy' => 120,
                'tong_chi_tieu' => 1200000,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(25),
                'updated_at' => $now->copy()->subDays(25),
            ],
            [
                'ten_khach_hang' => 'Ngô Thị K',
                'so_dien_thoai' => '0901234567',
                'email' => 'ngothik@example.com',
                'dia_chi' => '12 Trần Phú, Hà Đông, Hà Nội',
                'cong_no' => 0,
                'phi_chu' => null,
                'diem_tich_luy' => 45,
                'tong_chi_tieu' => 450000,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(22),
                'updated_at' => $now->copy()->subDays(22),
            ],
            [
                'ten_khach_hang' => 'Dương Văn L',
                'so_dien_thoai' => '0902345678',
                'email' => 'duongvanl@example.com',
                'dia_chi' => '78 Xô Viết Nghệ Tĩnh, Bình Thạnh, TP.HCM',
                'cong_no' => 0,
                'phi_chu' => null,
                'diem_tich_luy' => 250,
                'tong_chi_tieu' => 2500000,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(20),
                'updated_at' => $now->copy()->subDays(20),
            ],
            [
                'ten_khach_hang' => 'Lý Thị M',
                'so_dien_thoai' => '0903456789',
                'email' => 'lythim@example.com',
                'dia_chi' => '23 Phan Chu Trinh, Hoàn Kiếm, Hà Nội',
                'cong_no' => 0,
                'phi_chu' => null,
                'diem_tich_luy' => 75,
                'tong_chi_tieu' => 750000,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(18),
                'updated_at' => $now->copy()->subDays(18),
            ],
            [
                'ten_khach_hang' => 'Trương Văn N',
                'so_dien_thoai' => '0904567890',
                'email' => 'truongvann@example.com',
                'dia_chi' => '99 Lê Duẩn, Quận 1, TP.HCM',
                'cong_no' => 0,
                'phi_chu' => 'Khách doanh nghiệp',
                'diem_tich_luy' => 420,
                'tong_chi_tieu' => 4200000,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(15),
                'updated_at' => $now->copy()->subDays(15),
            ],
            [
                'ten_khach_hang' => 'Phan Thị O',
                'so_dien_thoai' => '0905678901',
                'email' => 'phanthio@example.com',
                'dia_chi' => '45 Nguyễn Trãi, Thanh Xuân, Hà Nội',
                'cong_no' => 0,
                'phi_chu' => null,
                'diem_tich_luy' => 60,
                'tong_chi_tieu' => 600000,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(12),
                'updated_at' => $now->copy()->subDays(12),
            ],
            [
                'ten_khach_hang' => 'Võ Văn P',
                'so_dien_thoai' => '0906789012',
                'email' => 'vovanp@example.com',
                'dia_chi' => '67 Điện Biên Phủ, Quận 3, TP.HCM',
                'cong_no' => 0,
                'phi_chu' => null,
                'diem_tich_luy' => 180,
                'tong_chi_tieu' => 1800000,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(10),
                'updated_at' => $now->copy()->subDays(10),
            ],
            [
                'ten_khach_hang' => 'Đinh Thị Q',
                'so_dien_thoai' => '0907890123',
                'email' => 'dinhthiq@example.com',
                'dia_chi' => '34 Lê Hồng Phong, Hải Châu, Đà Nẵng',
                'cong_no' => 0,
                'phi_chu' => null,
                'diem_tich_luy' => 110,
                'tong_chi_tieu' => 1100000,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(8),
                'updated_at' => $now->copy()->subDays(8),
            ],
            [
                'ten_khach_hang' => 'Hồ Văn R',
                'so_dien_thoai' => '0908901234',
                'email' => 'hovanr@example.com',
                'dia_chi' => '12 Trần Não, Quận 2, TP.HCM',
                'cong_no' => 0,
                'phi_chu' => null,
                'diem_tich_luy' => 35,
                'tong_chi_tieu' => 350000,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(6),
                'updated_at' => $now->copy()->subDays(6),
            ],
            [
                'ten_khach_hang' => 'Tô Thị S',
                'so_dien_thoai' => '0909012345',
                'email' => 'tothis@example.com',
                'dia_chi' => '56 Kim Mã, Ba Đình, Hà Nội',
                'cong_no' => 200000,
                'phi_chu' => 'Nợ hóa đơn 1 tuần',
                'diem_tich_luy' => 25,
                'tong_chi_tieu' => 250000,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(4),
                'updated_at' => $now->copy()->subDays(4),
            ],
            [
                'ten_khach_hang' => 'Châu Văn T',
                'so_dien_thoai' => '0910123456',
                'email' => 'chauvant@example.com',
                'dia_chi' => '89 Phan Xích Long, Phú Nhuận, TP.HCM',
                'cong_no' => 0,
                'phi_chu' => null,
                'diem_tich_luy' => 95,
                'tong_chi_tieu' => 950000,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(2),
                'updated_at' => $now->copy()->subDays(2),
            ],
            [
                'ten_khach_hang' => 'Tạ Thị U',
                'so_dien_thoai' => '0911234567',
                'email' => 'tathiu@example.com',
                'dia_chi' => '23 Nguyễn Thị Minh Khai, Quận 1, TP.HCM',
                'cong_no' => 0,
                'phi_chu' => 'Khách mới',
                'diem_tich_luy' => 0,
                'tong_chi_tieu' => 0,
                'trang_thai' => true,
                'created_at' => $now->copy()->subDays(1),
                'updated_at' => $now->copy()->subDays(1),
            ],
        ];

        DB::table('khach_hang')->insert($khachHangs);

        $this->command->info('[KhachHangSeeder] Da them '.count($khachHangs).' khach hang moi.');
    }
}