<?php

/*
 * Permission catalog used by seeders, middleware and Blade menus.
 * Existing module permissions are kept for backwards compatibility; action
 * permissions let administrators grant destructive operations independently.
 */
return [
    'groups' => [
        'dashboard' => ['xem_dashboard'],
        'ban_hang' => ['ban_hang'],
        'hoa_don' => [
            'quan_ly_hoa_don', 'xem_hoa_don', 'in_hoa_don',
            'doi_tra_hoa_don', 'huy_hoa_don',
        ],
        'san_pham' => [
            'quan_ly_san_pham', 'xem_san_pham', 'them_san_pham',
            'sua_san_pham', 'xoa_san_pham',
        ],
        'danh_muc' => [
            'quan_ly_danh_muc', 'xem_danh_muc', 'them_danh_muc',
            'sua_danh_muc', 'xoa_danh_muc',
        ],
        'kho_hang' => [
            'quan_ly_kho_hang', 'xem_kho_hang', 'nhap_hang', 'xuat_hang',
            'xoa_lo_hang', 'xoa_phieu_nhap', 'xoa_phieu_xuat',
            'kiem_kho_xem', 'kiem_kho_tao', 'kiem_kho_dem',
            'kiem_kho_duyet', 'kiem_kho_dieu_chinh', 'kiem_kho_huy',
        ],
        'hang_loi' => [
            'quan_ly_hang_loi', 'xem_hang_loi', 'them_hang_loi',
            'sua_hang_loi', 'xu_ly_hang_loi',
        ],
        'khach_hang' => [
            'quan_ly_khach_hang', 'xem_khach_hang', 'them_khach_hang',
            'sua_khach_hang', 'xoa_khach_hang',
        ],
        'khuyen_mai' => [
            'quan_ly_khuyen_mai', 'xem_khuyen_mai', 'them_khuyen_mai',
            'sua_khuyen_mai', 'xoa_khuyen_mai',
        ],
        'ca_lam' => ['quan_ly_ca_lam'],
        'nhan_su' => ['quan_ly_nhan_su'],
        'phan_quyen' => ['phan_quyen'],
        'cai_dat' => ['quan_ly_cai_dat'],
        'nha_cung_cap' => ['quan_ly_nha_cung_cap'],
    ],

    'labels' => [
        'xem_dashboard' => 'Xem thống kê',
        'ban_hang' => 'Bán hàng',
        'quan_ly_hoa_don' => 'Quản lý hóa đơn',
        'xem_hoa_don' => 'Xem hóa đơn',
        'in_hoa_don' => 'In hóa đơn',
        'doi_tra_hoa_don' => 'Xử lý đổi/trả hóa đơn',
        'huy_hoa_don' => 'Hủy hóa đơn',
        'quan_ly_san_pham' => 'Quản lý sản phẩm',
        'xem_san_pham' => 'Xem sản phẩm',
        'them_san_pham' => 'Thêm sản phẩm',
        'sua_san_pham' => 'Sửa sản phẩm',
        'xoa_san_pham' => 'Xóa sản phẩm',
        'quan_ly_danh_muc' => 'Quản lý danh mục',
        'xem_danh_muc' => 'Xem danh mục',
        'them_danh_muc' => 'Thêm danh mục',
        'sua_danh_muc' => 'Sửa danh mục',
        'xoa_danh_muc' => 'Xóa danh mục',
        'quan_ly_kho_hang' => 'Quản lý kho hàng',
        'xem_kho_hang' => 'Xem kho hàng',
        'nhap_hang' => 'Nhập hàng',
        'xuat_hang' => 'Xuất hàng',
        'xoa_lo_hang' => 'Xóa lô hàng',
        'xoa_phieu_nhap' => 'Xóa phiếu nhập',
        'xoa_phieu_xuat' => 'Xóa phiếu xuất',
        'quan_ly_hang_loi' => 'Quản lý hàng lỗi',
        'xem_hang_loi' => 'Xem hàng lỗi',
        'them_hang_loi' => 'Thêm hàng lỗi',
        'sua_hang_loi' => 'Sửa hàng lỗi',
        'xu_ly_hang_loi' => 'Xử lý hàng lỗi',
        'quan_ly_khach_hang' => 'Quản lý khách hàng',
        'xem_khach_hang' => 'Xem khách hàng',
        'them_khach_hang' => 'Thêm khách hàng',
        'sua_khach_hang' => 'Sửa khách hàng',
        'xoa_khach_hang' => 'Xóa khách hàng',
        'quan_ly_khuyen_mai' => 'Quản lý khuyến mãi',
        'xem_khuyen_mai' => 'Xem khuyến mãi',
        'them_khuyen_mai' => 'Thêm khuyến mãi',
        'sua_khuyen_mai' => 'Sửa khuyến mãi',
        'xoa_khuyen_mai' => 'Xóa khuyến mãi',
        'quan_ly_ca_lam' => 'Quản lý ca làm',
        'quan_ly_nhan_su' => 'Quản lý nhân sự',
        'phan_quyen' => 'Phân quyền',
        'quan_ly_cai_dat' => 'Quản lý cài đặt',
        'quan_ly_nha_cung_cap' => 'Quản lý nhà cung cấp',
        'kiem_kho_xem' => 'Xem kiểm kho',
        'kiem_kho_tao' => 'Tạo phiếu kiểm kho',
        'kiem_kho_dem' => 'Kiểm đếm hàng',
        'kiem_kho_duyet' => 'Duyệt phiếu kiểm kho',
        'kiem_kho_dieu_chinh' => 'Điều chỉnh tồn kho từ kiểm kho',
        'kiem_kho_huy' => 'Hủy phiếu kiểm kho',
    ],

    'truong_ca' => [
        'xem_dashboard',
        'ban_hang',
        'quan_ly_hoa_don', 'xem_hoa_don', 'in_hoa_don', 'doi_tra_hoa_don',
        'quan_ly_san_pham', 'xem_san_pham', 'them_san_pham', 'sua_san_pham',
        'quan_ly_danh_muc', 'xem_danh_muc', 'them_danh_muc', 'sua_danh_muc',
        'quan_ly_kho_hang', 'xem_kho_hang', 'nhap_hang',
        'kiem_kho_xem', 'kiem_kho_tao', 'kiem_kho_dem',
        'quan_ly_hang_loi', 'xem_hang_loi', 'them_hang_loi', 'sua_hang_loi',
        'xu_ly_hang_loi',
        'quan_ly_khach_hang', 'xem_khach_hang', 'them_khach_hang', 'sua_khach_hang',
        'quan_ly_khuyen_mai', 'xem_khuyen_mai', 'them_khuyen_mai', 'sua_khuyen_mai',
        'quan_ly_ca_lam',
    ],
];
